[package]
name="scratchpad"
version.workspace=true
edition.workspace=true
rust-version.workspace=true
license.workspace=true
[dependencies]
anyhow.workspace=true
clap.workspace=true
serde_json.workspace=true
scratchpad-core={path="../scratchpad-core"}
tokio.workspace=true
url.workspace=true
uuid.workspace=true
