use gtk::prelude::*; use gtk::glib; use scratchpad_core::*; use std::{cell::RefCell,rc::Rc,time::Duration};
#[cfg(feature="layer-shell")] use gtk4_layer_shell::{Edge,Layer,LayerShell};

fn main(){let app=gtk::Application::builder().application_id("dev.systemscratchpad.Scratchpad").build();app.connect_activate(build);app.run();}
fn build(app:&gtk::Application){let state=Rc::new(RefCell::new(UiState::default()));let win=gtk::ApplicationWindow::builder().application(app).title("Scratchpad").default_width(panel_width()).default_height(760).build();configure_shell(&win);let root=gtk::Box::new(gtk::Orientation::Horizontal,0);root.add_css_class("scratchpad");let rail=gtk::Box::new(gtk::Orientation::Vertical,6);rail.set_width_request(58);rail.add_css_class("page-rail");let content=gtk::Box::new(gtk::Orientation::Vertical,10);content.set_hexpand(true);let header=gtk::Label::new(Some("Scratchpad"));header.set_xalign(0.0);header.add_css_class("title-2");content.append(&header);let scroll=gtk::ScrolledWindow::new();let flow=gtk::FlowBox::new();flow.set_selection_mode(gtk::SelectionMode::None);flow.set_max_children_per_line(3);flow.set_row_spacing(10);flow.set_column_spacing(10);scroll.set_child(Some(&flow));scroll.set_vexpand(true);content.append(&scroll);root.append(&rail);root.append(&content);win.set_child(Some(&root));install_css();load_pages_and_items(&rail,&flow,state);win.present();}

fn load_pages_and_items(rail:&gtk::Box,flow:&gtk::FlowBox,state:Rc<RefCell<UiState>>){let paths=Paths::discover();let rail=rail.clone();let flow=flow.clone();glib::idle_add_local_once(move || { match ipc(&paths,Request::ListPages){Ok(Response::Pages(pages))=>{for p in pages {let b=gtk::Button::with_label(&page_glyph(&p.name));b.set_tooltip_text(Some(&p.name));b.add_css_class("page-dot");let pid=p.id;let f=flow.clone();let s=state.clone();b.connect_clicked(move |_|{s.borrow_mut().active=Some(pid);load_page(pid,&f);});install_hover_switch(&b,pid,flow.clone(),state.clone());rail.append(&b);if state.borrow().active.is_none(){state.borrow_mut().active=Some(pid);load_page(pid,&flow);}}},_=>{let l=gtk::Label::new(Some("Daemon offline"));rail.append(&l);}}});}
fn load_page(id:uuid::Uuid,flow:&gtk::FlowBox){while let Some(c)=flow.first_child(){flow.remove(&c);}let f=flow.clone();glib::idle_add_local_once(move || { let paths=Paths::discover(); if let Ok(Response::Page(s))=ipc(&paths,Request::GetPage{page_id:id}) { for (o,_) in s.items { f.insert(&card(&o),-1); } } });}
fn card(o:&Object)->gtk::Widget{let box_=gtk::Box::new(gtk::Orientation::Vertical,6);box_.set_width_request(210);box_.set_height_request(138);box_.add_css_class("object-card");let icon=gtk::Label::new(Some(icon_for(&o.kind)));icon.add_css_class("preview-icon");box_.append(&icon);let title=gtk::Label::new(Some(o.title.as_deref().unwrap_or("Untitled")));title.set_wrap(true);title.set_xalign(0.0);title.add_css_class("heading");box_.append(&title);let meta=gtk::Label::new(Some(&format!("{} • {} repr",kind_name(&o.kind),o.representations.len())));meta.set_xalign(0.0);meta.add_css_class("dim-label");box_.append(&meta);box_.upcast()}
fn install_hover_switch(b:&gtk::Button,page:uuid::Uuid,flow:gtk::FlowBox,state:Rc<RefCell<UiState>>){let motion=gtk::DropControllerMotion::new();let pending=Rc::new(RefCell::new(None::<glib::SourceId>));{let p=pending.clone();let s=state.clone();let f=flow.clone();motion.connect_enter(move|_,_,_|{if let Some(old)=p.borrow_mut().take(){old.remove();}let s2=s.clone();let f2=f.clone();*p.borrow_mut()=Some(glib::timeout_add_local_once(Duration::from_millis(hover_ms()),move||{s2.borrow_mut().active=Some(page);load_page(page,&f2);}));});}{let p=pending.clone();motion.connect_leave(move |_|{if let Some(old)=p.borrow_mut().take(){old.remove();}});}b.add_controller(motion);}

#[derive(Default)] struct UiState{active:Option<uuid::Uuid>}
fn ipc(paths:&Paths,req:Request)->anyhow::Result<Response>{
    use std::io::{BufRead, BufReader, Write};
    use std::os::unix::net::UnixStream;
    let mut s=UnixStream::connect(&paths.socket)?;
    let e=RequestEnvelope::new(req);
    s.write_all(serde_json::to_string(&e)?.as_bytes())?;
    s.write_all(b"\n")?;
    let mut line=String::new();
    BufReader::new(s).read_line(&mut line)?;
    Ok(serde_json::from_str::<ResponseEnvelope>(&line)?.response)
}
#[cfg(feature="layer-shell")] fn configure_shell(w:&gtk::ApplicationWindow){if std::env::var_os("SCRATCHPAD_NO_LAYER_SHELL").is_some()||!gtk4_layer_shell::is_supported(){return;}w.init_layer_shell();w.set_namespace(Some("system-scratchpad"));w.set_layer(Layer::Overlay);let e=std::env::var("SCRATCHPAD_EDGE").unwrap_or_else(|_|"right".into());match e.as_str(){"left"=>w.set_anchor(Edge::Left,true),"top"=>w.set_anchor(Edge::Top,true),"bottom"=>w.set_anchor(Edge::Bottom,true),_=>w.set_anchor(Edge::Right,true)}w.set_anchor(Edge::Top,true);w.set_anchor(Edge::Bottom,true);w.set_exclusive_zone(0);}
#[cfg(not(feature="layer-shell"))] fn configure_shell(_: &gtk::ApplicationWindow){}
fn panel_width()->i32{std::env::var("SCRATCHPAD_PANEL_WIDTH").ok().and_then(|x|x.parse().ok()).unwrap_or(430)} fn hover_ms()->u64{std::env::var("SCRATCHPAD_HOVER_MS").ok().and_then(|x|x.parse().ok()).unwrap_or(400)}
fn kind_name(k:&ObjectKind)->&'static str{match k{ObjectKind::Text=>"Text",ObjectKind::Url=>"URL",ObjectKind::Image=>"Image",ObjectKind::Video=>"Video",ObjectKind::Audio=>"Audio",ObjectKind::Pdf=>"PDF",ObjectKind::File=>"File",ObjectKind::Directory=>"Folder",ObjectKind::App=>"App",ObjectKind::Tool=>"Tool",ObjectKind::Unknown=>"Object"}} fn icon_for(k:&ObjectKind)->&'static str{match k{ObjectKind::Text=>"≡",ObjectKind::Url=>"↗",ObjectKind::Image=>"▧",ObjectKind::Video=>"▶",ObjectKind::Audio=>"♫",ObjectKind::Pdf=>"PDF",ObjectKind::File=>"▤",ObjectKind::Directory=>"▰",ObjectKind::App=>"◈",ObjectKind::Tool=>"⚙",ObjectKind::Unknown=>"◇"}} fn page_glyph(s:&str)->String{s.chars().next().map(|c|c.to_uppercase().collect()).unwrap_or_else(||"•".into())}
fn install_css(){let p=gtk::CssProvider::new();p.load_from_data(".scratchpad{background:#15171c;padding:10px}.page-rail{padding:6px}.page-dot{min-width:38px;min-height:38px;border-radius:12px}.object-card{background:#222630;border-radius:14px;padding:12px}.preview-icon{font-size:28px}.dim-label{opacity:.65}");gtk::style_context_add_provider_for_display(&gtk::gdk::Display::default().unwrap(),&p,gtk::STYLE_PROVIDER_PRIORITY_APPLICATION);}
